[workspace]
members = [
	"bee-common/bee-common",
	"bee-common/bee-common-derive",
	"bee-crypto",
	"bee-runtime",
	"bee-network",
	"bee-signing",
	"bee-storage/bee-storage",
	"bee-ternary",
	"bee-test",
]
