[package]
name = "bee-test"
version = "0.1.0-alpha"
authors = ["IOTA Stiftung"]
edition = "2018"
description = "Test utilities and feature tests for bee"
readme = "README.md"
repository = "https://github.com/iotaledger/bee"
license = "Apache-2.0"
keywords = ["iota", "tangle", "bee", "framework", "test"]
homepage = "https://www.iota.org"

[dependencies]
bee-storage = { version = "0.2.0-alpha", path = "../bee-storage/bee-storage" }
bee-ternary = { version = "0.3.4-alpha", features = [ "serde1" ], path = "../bee-ternary" }

async-trait = "0.1"
rand = "0.7"
serde = { version = "1.0", features = ["derive" ] }

[dev-dependencies]
serde = "1.0"
serde_json = "1.0"
